#!/bin/bash
D1=$(date +%s --date="20:00 19/12/2011")
#D1=$(date +%s --date="$(date +%X)")
D2=$(date +%s --date="20:00 26/12/2011")
date -u --date=@$((D2-D1)) +%X


#$ D1="12:23 13/01/2008"
#$ D2="13:23 13/01/2008"
#$ SDIFF=$((`date -d "$D2" '+%s'` - `date -d "$D1" '+%s'`))
#$ echo $SDIFF
#3600
